version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=jigsaw
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
